---
#=========== LOCALE SETUP ============
- name: "[Debian] Set {{ rpi_bootstrap_locale }} locale"
  community.general.locale_gen:
    name: "{{ rpi_bootstrap_locale }}"
    state: present
  become: true
  tags: rpi_bootstrap
#=====================================

#========== DISTRO UPGRADE ===========
- name: "[Debian] Full upgrade (including firmware to the latest STABLE version)"
  ansible.builtin.apt:
    upgrade: full
    autoclean: true
    autoremove: true
  become: true
  register: rpi_bootstrap_upgrade_result
  until: rpi_bootstrap_upgrade_result is succeeded
  when: "'Debian' in ansible_os_family"
  tags: rpi_bootstrap
#=====================================

#========= UPDATING FIRMWARE: ========
- name: "[Debian] Installing latest rpi-update"
  ansible.builtin.apt:
    name: rpi-update
    state: latest
    force: true
  become: true
  register: rpi_bootstrap_upgrade_result
  until: rpi_bootstrap_upgrade_result is succeeded
  when:
    - rpi_bootstrap_firmware_update_to_bleeding_edge
    - "'Debian' in ansible_os_family"
  tags: rpi_bootstrap

- name: "[Debian] Updating firmware to Bleeding edge (MAY BE UNSTABLE)"
  ansible.builtin.shell: yes | rpi-update
  become: true
  when:
    - rpi_bootstrap_firmware_update_to_bleeding_edge
    - "'Debian' in ansible_os_family"
  tags: rpi_bootstrap
#=====================================
